language:
  - c
before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get update
  - sudo apt-get install linuxdoc-tools linuxdoc-tools-info binutils-mingw-w64-i686 gcc-mingw-w64-i686 sshpass cmake
script:
  - mkdir _build && cd _build && cmake -DUSE_OPENCL=OFF .. && make -j 8 all
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
